name: Build iOS Dev IPA

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install JS dependencies
        run: npm install

      - name: Install CocoaPods
        run: |
          cd ios
          pod install

      - name: Clean Xcode build
        run: |
          cd ios
          xcodebuild clean \
            -workspace NiteLight.xcworkspace \
            -scheme NiteLight

      - name: Build iOS app
        run: |
          cd ios

          xcodebuild \
            -workspace NiteLight.xcworkspace \
            -scheme NiteLight \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO \
            ENABLE_DEBUG_DYLIB=NO

      - name: Create IPA
        run: |
          mkdir Payload

          cp -r ios/build/Build/Products/Release-iphoneos/NiteLight.app Payload/

          cd Payload/..
          zip -r NiteLight.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: NiteLight.ipa